services:
  api:
    build:
      context: .
    container_name: typescript-application
    environment:
      DATABASE_URL: "file:../../data/app.db"
    volumes:
      - ./data:/app/data
    ports:
      - '8000:8000'
    restart: "no"
